### ISSUE TITLE
question about number of samples generated for each candidate

### ISSUE THREAD

**Issue by sihouzi21c** [lilijiangg/AutoDiffusion#2]
In your paper, it is said that 'The optimal number of samples is the minimum N_sam that makes Kendall-tau greater than 0.5.' However in 'search_dynamic_unet_imagenet64_classifier_guidance_progressive.py' file, I find the number of N_sam is set to 100. Is the number calculated before searching?

**Comment by lilijiangg** [comment]
Thank you for pointing out this problem. You're correct, the error may have occurred because the author did not update the parameter used during debugging. In all experiments mentioned in the paper, 'N_sam' was set to values between 1000 to 5000. I've made the necessary corrections in the code.

**Comment by sihouzi21c** [comment]
Thanks a lot!
