### ISSUE TITLE
About ref_stats in 'evaluator_v1.py'

### ISSUE THREAD

**Issue by sihouzi21c** [lilijiangg/AutoDiffusion#5]
In 'evaluator_v1.py' line 49 to 52, there refers to 'ref_stats_test.pkl' and 'ref_stats_spatial_test.pkl'. However the Google drive only provides 'imagenet_ref_stats.pkl'. Could you offer the download of these two pkl files? Thanks a lot.

**Comment by lilijiangg** [comment]
Thanks for pointing this out. The `main` function in `evaluator_v1.py` (lines 27-102) isn't actually called during the search process. You can safely comment it out. Sorry for the oversight and confusion.

**Comment by sihouzi21c** [comment]
Thanks a lot!
