### ISSUE TITLE
Create Other FID Stats for Performance Estimation

### ISSUE THREAD

**Issue by qianlong0502** [lilijiangg/AutoDiffusion#7]
You offer 3 files of FID stats for performance estimation during search. However, I'd like to ask how to create my own FID stat?

**Comment by qianlong0502** [comment]
I understand that the FID stat is calculated by `Evaluator.compute_statistics`. I want to make sure whether you select fixed number of sample from dataset **randomly**?

**Comment by lilijiangg** [comment]
Thanks for your question. When calculating FID stats, we use complete reference batches provided by Guided-Diffusion codebase, accessible here: https://github.com/openai/guided-diffusion/tree/main/evaluations.

**Comment by qianlong0502** [comment]
Thanks for your reply. The reference batches provided by Guided-Diffusion codebase are `.npz` files. The FID stats you used is class `FIDStatistics`, which is loaded by `pickle`. It is obvious that the instance of `FIDStatistics` is calculated by a subset of `.npz` file. (or, am I wrong?) Would you like to share how you construct this `FIDStatistics` class and save it?

For example, now, I trained a diffusion model on dataset cifar10 and I want to search better timestep sequences by using your algorithm. However, I found that I must specify `--ref_path`.  How can I get FID stat file related to `--ref_path`?

**Comment by lilijiangg** [comment]
We apologize for any confusion, and currently, we don't have dedicated code for computing FID stats separately.  In all our experiments, FID stats are computed using [evaluation.py](https://github.com/lilijiangg/AutoDiffusion/tree/main/examples/guided_diffusion/evaluations/evaluator.py). Specifically, at line 50 in the code, you'll find the computation of FID stats. We simply inserted the code to save FID stats after this line.

To obtain FID stats for CIFAR-10, you can modify the save path at line 53 in evaluation.py. Then, convert the CIFAR-10 dataset to .npz file and use the following script:
```
python ./evaluations/evaluation.py cifar10.npz other.npz
```
In this example, if you're only interested in obtaining FID stats, you can substitute any data for `other.npz`.

**Comment by qianlong0502** [comment]
You mean `evaluator.py` right? I follow your cmd  and get a resultant FID stat file:

lines 53-55 are:

```python
f = open('imagenet_official_ref_stats.pkl','wb')
pickle.dump(ref_stats, f)
f.close()
```

Here I obtained `imagenet_official_ref_stats.pkl` and then I use your script for searching by modifying the flag `--ref_path` to `path/to/imagenet_official_ref_stats.pkl`. The number of timesteps is 5.

A part of the final output is:

```bash
....
select ......
epoch = 9 : top 50 result
No.1 [625, 0, 974, 571, 647] fid = 219.89347407563767
No.2 [492, 0, 974, 571, 647] fid = 221.20143159529346
No.3 [724, 0, 974, 571, 533] fid = 221.74197446245955
No.4 [492, 0, 974, 676, 647] fid = 222.31295939290743
No.5 [492, 0, 974, 571, 737] fid = 222.86101141198486
No.6 [835, 0, 974, 571, 647] fid = 223.16064900263854
......
```

I got several questions:

Firstly, the top1 fid is very high, is that similar with your experiment?

Secondly, I use the searched result to sample, and get these result:

- Your sample code, use ddim, searched timesteps, fid is 216
- Your sample code, do not use ddim, searched timesteps, fid is 254
- Code of OpenAI (guided-diffusion), searched timesteps, fid is 107
- Code of OpenAI (guided-diffusion), default 5 timesteps, fid is 41

Did I make any mistakes that resulted in discrepancies with Table 2-3 in your paper?

**Comment by lilijiangg** [comment]
I suspect the problem stem from inaccuracies in the FID evaluation during the search process. Could you share the script you used for running the search? Additionally, I'd like details on the data used for computing the FID stats. I will try to resolving this issue promptly.

**Comment by qianlong0502** [comment]
I really appreciate your help!

### script

Here the only thing I changed is `MODEL_FLAGS` and some path-related params.

```shell
MODEL_FLAGS="--attention_resolutions 16,8 --class_cond False --diffusion_steps 1000 --dropout 0.3 --image_size 32 --learn_sigma True --noise_schedule cosine --num_channels 128 --num_head_channels 32 --num_res_blocks 3 --resblock_updown True --use_fp16 True --use_scale_shift_norm True"
SAMPLE_FLAGS="--batch_size 1024 --num_samples 3000 --use_ddim True"

CUDA_VISIBLE_DEVICES=0 \
python search_uncondition_model.py $MODEL_FLAGS \
--model_path 'model/32x32_diffusion_cifar10.pt' $SAMPLE_FLAGS \
--save_dir './exps/cifar10/ea_search_ddim/timestep15_m_prob0.25_numsample3000' \
--time_step 5 \
--max_epochs 10 \
--population_num 50 \
--mutation_num 25 \
--crossover_num 10 \
--seed 0 \
--m_prob 0.25 \
--ref_path 'stats/cifar10_ref_stats.pkl' \
--use_ddim_init_x True \
--MASTER_PORT '12345' \
```

The checkpoint of the pre-trained model on cifar10 comes from [DDPM-IP](https://drive.google.com/file/d/1m-a3WqfpMTibzuTC2om046yWQr20GT0I/view), which are released in this [repo](https://github.com/forever208/DDPM-IP).

### Dataset

The dataset I use is training set of cifar10, which contains 50k image. You can download by the [script](https://github.com/forever208/DDPM-IP/blob/DDPM-IP/datasets/cifar10.py) in aforementioned [repo](https://github.com/forever208/DDPM-IP).

#### Get `npz` file

Use this script:

```python
import os
import cv2
import numpy as np

def imgs_to_npz():
    npz = []

    for img in os.listdir("./cifar"):
        img_arr = cv2.imread("./cifar/" + img)
        img_arr = cv2.cvtColor(img_arr, cv2.COLOR_BGR2RGB)
        npz.append(img_arr)

    output_npz = np.array(npz)
    np.savez('cifar10_train.npz', output_npz)
    print(f"{output_npz.shape} size array saved into cifar10_train.npz")

if __name__ == '__main__':
    imgs_to_npz()
```

**Comment by lilijiangg** [comment]
I think the main issue contributing to the high FID values may be related to the `MODEL_FLAGS` configuration. Considering that the model weights are derived from DDPM-IP, adjusting the parameters to align with [DDPM-IP's configuration](https://github.com/forever208/DDPM-IP#sampling-from-pre-trained-adm-ip-models) may yield more accurate FID results.

### Sampling
Specifically, for the `MODEL_FLAGS` in your script:
```
MODEL_FLAGS="--attention_resolutions 16,8 --class_cond False --diffusion_steps 1000 --dropout 0.3 --image_size 32 --learn_sigma True --noise_schedule cosine --num_channels 128 --num_head_channels 32 --num_res_blocks 3 --resblock_updown True --use_fp16 True --use_scale_shift_norm True"
```
The resulting FID was 266.30.
However, using DDIM-IP's configuration, with a modification to `timestep_respacing` from the original `100` to `ddim5`, as follows:
```
python scripts/image_sample.py \
--image_size 32 --timestep_respacing ddim5 --use_ddim True \
--model_path './ADM_cifar10_baseline.pt' \
--num_channels 128 --num_head_channels 32 --num_res_blocks 3 --attention_resolutions 16,8 \
--resblock_updown True --use_new_attention_order True --learn_sigma True --dropout 0.3 \
--diffusion_steps 1000 --noise_schedule cosine --use_scale_shift_norm True --batch_size 2048 --num_samples 50000 \
--save_dir './debug1/samples' \
--port '12346' \
```
The resulting FID improved significantly to 29.12.
### Search for optimal time steps
When using DDIM-IP's configuration for the search process, the expected results were achieved. The entire search script is provided below:
```
SAMPLE_FLAGS="--batch_size 1024 --num_samples 3000 --use_ddim True"

CUDA_VISIBLE_DEVICES=0 \
python search_uncondition_model.py \
--model_path 'model/32x32_diffusion_cifar10.pt' $SAMPLE_FLAGS \
--save_dir './exps/cifar10/ea_search_ddim/timestep15_m_prob0.25_numsample3000' \
--time_step 5 \
--max_epochs 10 \
--population_num 50 \
--mutation_num 25 \
--crossover_num 10 \
--seed 0 \
--m_prob 0.25 \
--ref_path './cifar10.pkl' \
--use_ddim_init_x True \
--MASTER_PORT '12345' \
--image_size 32 --use_ddim True \
--model_path './ADM_cifar10_baseline.pt' \
--num_channels 128 --num_head_channels 32 --num_res_blocks 3 --attention_resolutions 16,8 \
--resblock_updown True --use_new_attention_order True --learn_sigma True --dropout 0.3 \
--diffusion_steps 1000 --noise_schedule cosine --use_scale_shift_norm True
```

The top-10 candidates are:
```
epoch = 9 : top 50 result
No.1 [611, 834, 772, 156, 362] fid = 29.621596491404148
No.2 [758, 315, 891, 633, 144] fid = 29.885007453962203
No.3 [140, 315, 889, 625, 747] fid = 29.94638133002877
No.4 [381, 834, 277, 633, 144] fid = 30.059256388441895
No.5 [611, 834, 772, 156, 444] fid = 30.25652283985869
No.6 [381, 834, 891, 633, 144] fid = 30.354665249213326
No.7 [574, 375, 772, 156, 823] fid = 30.381748888973334
No.8 [574, 834, 772, 156, 444] fid = 30.449450571452473
No.9 [758, 315, 891, 625, 144] fid = 30.461538543591928
No.10 [140, 229, 889, 464, 747] fid = 30.484714943699657
```
I've uploaded the [log.txt](https://github.com/lilijiangg/AutoDiffusion/files/13406864/log.txt) file from the search process to assist you further.

**Comment by qianlong0502** [comment]
Thank you very much! There is no problem now. 😃
